language: ruby

cache:
- bundler
- apt

os:
- linux

sudo: required
dist: trusty

rvm:
#rbx doesnt work anymore with rwx
#- rbx-2.2.7
#rbx does not have a head
#- rbx-head
- 2.1.8
- 2.2.4
- 2.3.0
- ruby-head


before_script:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_script-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_script-osx.sh; fi"


before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"


matrix:
  allow_failures:
    - os: osx
    - rvm: ruby-head
