language: ruby

cache:
- bundler
- apt

os:
- linux
- osx

rvm:
#rbx doesnt work anymore with rwx
#- rbx-2.2.7
#rbx does not have a head
#- rbx-head
#- 2.1.1-clang
- 2.1.0
- 2.1.0-clang
#- 2.1.3-clang
- 2.1.6
- 2.1.6-clang
- 2.2.0
- 2.2.0-clang
- 2.2.2
- 2.2.2-clang

- ruby-head
- ruby-head-clang

before_script:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_script-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_script-osx.sh; fi"


before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then . ./ci/travis/before_install-linux.sh; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then . ./ci/travis/before_install-osx.sh; fi"


matrix:
  exclude:
    - rvm: 2.1.0
      os: osx
    - rvm: 2.1.0-clang
      os: linux
    - rvm: 2.1.6
      os: osx
    - rvm: 2.1.6-clang
      os: linux
    - rvm: 2.2.0
      os: osx
    - rvm: 2.2.0-clang
      os: linux
    - rvm: 2.2.2
      os: osx
    - rvm: 2.2.2-clang
      os: linux
    - rvm: ruby-head
      os: osx
    - rvm: ruby-head-clang
      os: linux
  allow_failures:
    - os: osx
