language: ruby

cache:
- bundler
- apt

rvm:
- rbx-2.2.7
#rbx does not have a head
#- rbx-head
#- 2.1.1-clang
- 2.1.0
- 2.1.1
#- 2.1.3-clang
- 2.1.5
#- ruby-head-clang
- 2.2.0
#currently broken because of data_type parent
- ruby-head

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3

before_install:
#- 'if [[ "$TRAVIS_RUBY_VERSION" =~ -clang ]]; then export CC=clang; fi'
- "sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc"
- "sudo add-apt-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe'"
- "sudo apt-get update"
- "sudo apt-get install -y libwxbase3.0-dev libwxgtk3.0-dev"
