language: ruby

cache:
- bundler
- apt

rvm:
- 2.0.0
- 2.1.3
- ruby-head

before_script:
  - sudo add-apt-repository ppa:costamagnagianfranco/locutusofborg-ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libwxgtk3.0-dev libwxgtk-media3.0-dev
